### ISSUE TITLE
Suggestion: submodule bosh-deployment

### ISSUE THREAD

**Issue by drnic** [concourse/concourse-bosh-deployment#1]
Instead of manually maintaining infrastructures/ folder, perhaps submodule bosh-deployment and use its cpi files?

**Comment by danger-ranger** [comment]
That won't work out-of-the-box since the bosh-deployment cpi.yml's need to be modified to work for the concourse deployment. But it might be worth trying to either a) script the modification of the ops file, since it's fairly trivial or b) split the ops files in bosh-deployment up into two files, one with the stuff we want and one with the stuff we don't want.

**Comment by topherbullock** [comment]
@drnic out of the box it won't work, since those ops files expect an instance group named "bosh".

```
~/w/paper-plane$ bosh interpolate ./concourse-paper-plane.yml -o ../bosh-deployment/gcp/cpi.yml
Expected to find exactly one matching array item for path '/instance_groups/name=bosh' but found 0
Exit code 1
```

This would require 2 ops files either way, and would complicate either our ops files or bosh-deployment's, ops files by requiring a split in the `cloud_provider` and `instance_groups` operations.
