### ISSUE TITLE
pull releases from bosh.io

### ISSUE THREAD

**Issue by zmb3** [concourse/concourse-bosh-deployment#17]
I'm a little confused as to the source of the releases.

It looks like they started out coming from bosh.io and were [moved to Github](https://github.com/concourse/concourse-deployment/commit/194bf9571623b1b66fcff1376cba5436dd3b101f), and then later that same day garden-runc was [moved back to bosh.io](https://github.com/concourse/concourse-deployment/commit/26dd85099a4bf8de93311062afbd1506370b7a27), but concourse remains at Github.

I'm unable to `create-env` without changing the Concourse release back to bosh.io.  The download from Github eventually hangs.

Is there a reason why the Concourse release is still downloaded from Github?  Can we change this back to bosh.io?

**Comment by vito** [comment]
This repository is now used for building our single-vm Concourse Lite box. Because of the delay on `bosh.io`, we can't know the SHA for the URL at the time we're generating and publishing the .yml file. We can know this for Garden-runC, because we depend on it (and it's already published), but we can't for our own.
