### ISSUE TITLE
5.5.6 release

### ISSUE THREAD

**Issue by JasonMorgan** [concourse/concourse-bosh-deployment#193]
Hey folks, the pivotal docs for concourse instruct users to checkout v5.5.6, you can see that [here](https://docs.pivotal.io/p-concourse/v5/installation/install-concourse-bosh/). Unfortunately, according to the [releases page](https://github.com/concourse/concourse-bosh-deployment/releases?after=v5.5.0), there is not currently a 5.5.6 release. I figure someone ought to adjust something to make those two things match.

**Comment by xtreme-sameer-vohra** [comment]
Hey @JasonMorgan 
Thanks for reporting this. There is a tag for [v5.5.6](https://github.com/concourse/concourse-bosh-deployment/tree/v5.5.6) available now. I have also submitted a PR to update the docs to refer to a `tag` rather than `release` as in our current work flow, we typically create `tags` for `concourse-bosh-deployment`.

**Comment by xtreme-sameer-vohra** [comment]
I am going to close this issue as solved. 
But please feel free to create a new issue if you feel your concern was not addressed.
