### ISSUE TITLE
v6.1.0 - tagged incorrectly in this repo - Concourse unable to track

### ISSUE THREAD

**Issue by ghost** [concourse/concourse-bosh-deployment#218]
We use a Concourse pipeline to track changes to this repo to notify us of Concourse updates, and then kick them off. We use the `git-resource` to track the `master` branch with a `tag_filter` of `v*` and this has worked well for some time.

Normally your tags (such as `v6.0.0`) are applied to commits on the `master` branch.

However the commit tagged as `v6.1.0` yesterday is not on the `master` branch (I suspect it may have been tagged prior to a merge)?

This means that anyone using the Concourse `git-resource` is unlikely to detect this update, if they are using a tag filter on the master branch.

**Comment by vito** [comment]
Here's what happened:

1. With v6.1.x we tweaked our release process so we always ship from release pipelines, rather than shipping releases that "roll forward" (i.e. latest -> latest) from our main pipeline.
1. Release pipelines have a `bump-cbd-versions` job which created https://github.com/concourse/concourse-bosh-deployment/commit/96dea5552ab589e17cc925bfca578ee1c71e4501 on the `release/x.x.x` branch of this repo and tagged it as `v6.1.0`.
    * In the past, these commits have always been for non-latest releases, but this time it was for v6.1.0.
1. The master pipeline *also* has a `bump-cbd-versions` job, which triggers whenever a new release appears on bosh.io.
    * Normally, this job wouldn't fire when shipping from a release pipeline, because patch releases of older versions wouldn't trigger the job. In this case, a new 'latest' release was shipped, so it triggered the job in addition to the release pipeline's own 'bump' job.

So, when the main pipeline's `bump-cbd-versions` job triggered, it created and pushed https://github.com/concourse/concourse-bosh-deployment/commit/022e40ac3db05d0193fdf2eb9050a71e904abce7 to master, but then it got stuck in a loop pushing the `v6.1.0` tag because it already exists. [The build](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bump-cbd-versions/builds/5) ran in a loop for 3 days before finally failing.

It was tempting for me to say "just don't track the `master` branch - track all branches" but it turns out the order of the versions isn't exactly useful to track - it's chronologically sorted, not semver sorted:

![image](https://user-images.githubusercontent.com/1880/83535135-a4dee000-a4bf-11ea-860d-47cefdb52da4.png)

...so, yeah, we'll look into fixing this. It's a little tricky. Maybe we just need to force-push the tag? 🤔

edit: maybe a better idea would be to merge the `release/x.x.x` branch in. 🤔

**Comment by vito** [comment]
I've merged `release/6.1.x` into `master`, so the tag is there now! I'm going to close this issue and we'll have this flow sorted out for the next release. See https://github.com/concourse/concourse/issues/5633#issuecomment-637637942 for details.
